In [1]:
import pandas as pd

In [4]:
house = pd.read_csv('C:\Python\Python36-32\examples\hou_report_1_30.csv')

In [5]:
house.head()

,年月,地址,類型,總價,每坪單價,建坪,地坪,屋齡,樓層,格局
0,107年03月,南屯區黎明路二段421~450號 檢視位置,電梯大樓/住宅 含車位,770萬 (含車位80萬),18萬,42.7坪 (含車位--坪),4.06坪,22.4年,7 /共16層,3房/2廳/2衛/1室
1,107年03月,南屯區東興東街31~60號 檢視位置,華廈/住宅,400萬,15.4萬,26.03坪,4.48坪,27年,2 /共7層,3房/2廳/2衛/1室
2,107年03月,南屯區大英街241~270號 檢視位置,華廈/住宅 含車位,740萬 (含車位60萬),17.6萬 (扣除車位價及車坪),41.66坪 (含車位3.03坪),5.21坪,20.2年,8 /共9層,2房/2廳/2衛/1室 社區 熊熊新象 》
3,107年03月,南屯區五權西路二段1~30號 檢視位置,電梯大樓/住宅 含車位,1470萬 (含車位150萬),29萬 (扣除車位價及車坪),51.53坪 (含車位6坪),4.57坪,9.7年,10 /共15層,3房/2廳/2衛/0室 社區 惠宇清寬 》
4,107年02月,南屯區三和街61~90號 檢視位置,電梯大樓/住宅 含車位,1488萬 (含車位300萬),28.7萬 (扣除車位價及車坪),58.22坪 (含車位16.8坪),6.09坪,10.3年,8 /共14層,3房/2廳/2衛/0室 社區 惠宇城市遠見 》

In [10]:
for i in range(len(house['地址'])):
    house['地址'][i] = house['地址'][i][:-5]

In [9]:
house['地址'][15][:-5]

'南屯區龍德路一段121~150號'

In [11]:
house.head()

,年月,地址,類型,總價,每坪單價,建坪,地坪,屋齡,樓層,格局
0,107年03月,南屯區黎明路二段421~450號,電梯大樓/住宅 含車位,770萬 (含車位80萬),18萬,42.7坪 (含車位--坪),4.06坪,22.4年,7 /共16層,3房/2廳/2衛/1室
1,107年03月,南屯區東興東街31~60號,華廈/住宅,400萬,15.4萬,26.03坪,4.48坪,27年,2 /共7層,3房/2廳/2衛/1室
2,107年03月,南屯區大英街241~270號,華廈/住宅 含車位,740萬 (含車位60萬),17.6萬 (扣除車位價及車坪),41.66坪 (含車位3.03坪),5.21坪,20.2年,8 /共9層,2房/2廳/2衛/1室 社區 熊熊新象 》
3,107年03月,南屯區五權西路二段1~30號,電梯大樓/住宅 含車位,1470萬 (含車位150萬),29萬 (扣除車位價及車坪),51.53坪 (含車位6坪),4.57坪,9.7年,10 /共15層,3房/2廳/2衛/0室 社區 惠宇清寬 》
4,107年02月,南屯區三和街61~90號,電梯大樓/住宅 含車位,1488萬 (含車位300萬),28.7萬 (扣除車位價及車坪),58.22坪 (含車位16.8坪),6.09坪,10.3年,8 /共14層,3房/2廳/2衛/0室 社區 惠宇城市遠見 》

In [12]:
house.to_csv('C:\Python\Python36-32\examples\hou_report_1_30.csv', index = False)